import Vue from 'vue'
import {
  Button,
  Checkbox,
  CheckboxGroup,
  Col,
  Container,
  DatePicker,
  Form,
  FormItem,
  Header,
  Input,
  InputNumber,
  Link,
  Main,
  Option,
  Radio,
  RadioButton,
  RadioGroup,
  Row,
  Select,
  Switch,
  TimePicker
} from 'element-ui'
Vue.use(Button)
Vue.use(Row)
Vue.use(Container)
Vue.use(Main)
Vue.use(Header)
Vue.use(Col)
Vue.use(DatePicker)
Vue.use(TimePicker)
Vue.use(Link)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Radio)
Vue.use(RadioButton)
Vue.use(RadioGroup)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Input)
Vue.use(InputNumber)
Vue.use(Select)
Vue.use(Option)
Vue.use(Switch)